apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webpage-server
  name: webpage-server
spec:
  containers:
  - image: nginx:1.15
    name: webpage-server
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
