apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: twocontpod
  name: twocontpod
  namespace: mynamespace
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: twocontpod
###add extra from below####
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: twocontpodsec
